CREATE TABLE IF NOT EXISTS booking_records (
    booking_id VARCHAR(64) PRIMARY KEY,
    booking_number VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    revision INTEGER NOT NULL,
    customer_id VARCHAR(64) NOT NULL,
    origin_location_id VARCHAR(64) NOT NULL,
    destination_location_id VARCHAR(64) NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    snapshot TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_booking_records_booking_number
    ON booking_records(booking_number);

CREATE INDEX IF NOT EXISTS idx_booking_records_customer_status
    ON booking_records(customer_id, status);

CREATE TABLE IF NOT EXISTS booking_idempotency (
    idempotency_key VARCHAR(128) PRIMARY KEY,
    booking_id VARCHAR(64) NOT NULL REFERENCES booking_records(booking_id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS booking_audit (
    audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(64) NOT NULL,
    booking_id VARCHAR(64),
    actor_subject_id VARCHAR(128),
    result VARCHAR(32) NOT NULL,
    reason VARCHAR(256),
    correlation_id VARCHAR(128),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_booking_audit_booking
    ON booking_audit(booking_id, created_at);

CREATE TABLE IF NOT EXISTS booking_outbox (
    event_id VARCHAR(128) PRIMARY KEY,
    event_type VARCHAR(128) NOT NULL,
    booking_id VARCHAR(64) NOT NULL,
    booking_number VARCHAR(64) NOT NULL,
    revision INTEGER NOT NULL,
    schema_subject VARCHAR(128) NOT NULL,
    producer_identity VARCHAR(128) NOT NULL,
    deduplication_key VARCHAR(128) NOT NULL,
    correlation_id VARCHAR(128),
    occurred_at TIMESTAMP,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP,
    claimed_by VARCHAR(128),
    claimed_at TIMESTAMP,
    last_error_code VARCHAR(128),
    last_error_message VARCHAR(1024),
    snapshot TEXT NOT NULL
);

ALTER TABLE booking_outbox ADD COLUMN IF NOT EXISTS status VARCHAR(32) NOT NULL DEFAULT 'PENDING';
ALTER TABLE booking_outbox ADD COLUMN IF NOT EXISTS attempt_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE booking_outbox ADD COLUMN IF NOT EXISTS next_attempt_at TIMESTAMP;
ALTER TABLE booking_outbox ADD COLUMN IF NOT EXISTS claimed_by VARCHAR(128);
ALTER TABLE booking_outbox ADD COLUMN IF NOT EXISTS claimed_at TIMESTAMP;
ALTER TABLE booking_outbox ADD COLUMN IF NOT EXISTS last_error_code VARCHAR(128);
ALTER TABLE booking_outbox ADD COLUMN IF NOT EXISTS last_error_message VARCHAR(1024);

CREATE INDEX IF NOT EXISTS idx_booking_outbox_booking
    ON booking_outbox(booking_id, occurred_at);

CREATE INDEX IF NOT EXISTS idx_booking_outbox_claim
    ON booking_outbox(status, next_attempt_at, occurred_at);
