CREATE TABLE charge_agreements (
    id VARCHAR(64) PRIMARY KEY,
    agreement_number VARCHAR(64) NOT NULL,
    customer_id VARCHAR(64) NOT NULL,
    trade_lane_id VARCHAR(64) NOT NULL,
    commodity_id VARCHAR(64) NOT NULL,
    valid_from DATE NOT NULL,
    valid_to DATE NOT NULL,
    status VARCHAR(32) NOT NULL,
    version BIGINT NOT NULL,
    created_by VARCHAR(128),
    created_at TIMESTAMP,
    updated_by VARCHAR(128),
    updated_at TIMESTAMP
);

CREATE TABLE charge_agreement_terms (
    id VARCHAR(64) NOT NULL,
    agreement_id VARCHAR(64) NOT NULL REFERENCES charge_agreements(id),
    charge_code_id VARCHAR(64) NOT NULL,
    basis VARCHAR(32) NOT NULL,
    currency_id VARCHAR(64) NOT NULL,
    amount DECIMAL(18, 4) NOT NULL,
    valid_from DATE NOT NULL,
    valid_to DATE NOT NULL,
    notes VARCHAR(512),
    PRIMARY KEY (agreement_id, id)
);

CREATE TABLE charge_agreement_activity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agreement_id VARCHAR(64) NOT NULL REFERENCES charge_agreements(id),
    action VARCHAR(64) NOT NULL,
    actor VARCHAR(128) NOT NULL,
    occurred_at TIMESTAMP NOT NULL,
    reason VARCHAR(512)
);

CREATE INDEX idx_charge_agreements_customer_status_validity
    ON charge_agreements(customer_id, status, valid_from, valid_to);

CREATE INDEX idx_charge_agreements_lane_customer_validity
    ON charge_agreements(trade_lane_id, customer_id, valid_from, valid_to);
