CREATE TABLE charge_agreements (
    id VARCHAR(64) PRIMARY KEY,
    agreement_number VARCHAR(64) NOT NULL,
    customer_id VARCHAR(64) NOT NULL,
    trade_lane_id VARCHAR(64) NOT NULL,
    commodity_id VARCHAR(64) NOT NULL,
    valid_from DATE NOT NULL,
    valid_to DATE NOT NULL,
    status VARCHAR(32) NOT NULL,
    version BIGINT NOT NULL,
    created_by VARCHAR(128),
    created_at TIMESTAMP,
    updated_by VARCHAR(128),
    updated_at TIMESTAMP,
    snapshot TEXT
);

CREATE TABLE charge_agreement_terms (
    id VARCHAR(64) NOT NULL,
    agreement_id VARCHAR(64) NOT NULL REFERENCES charge_agreements(id),
    charge_code_id VARCHAR(64) NOT NULL,
    basis VARCHAR(32) NOT NULL,
    currency_id VARCHAR(64) NOT NULL,
    amount DECIMAL(18, 4) NOT NULL,
    valid_from DATE NOT NULL,
    valid_to DATE NOT NULL,
    notes VARCHAR(512),
    PRIMARY KEY (agreement_id, id)
);

CREATE TABLE charge_agreement_activity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agreement_id VARCHAR(64) NOT NULL REFERENCES charge_agreements(id),
    action VARCHAR(64) NOT NULL,
    actor VARCHAR(128) NOT NULL,
    occurred_at TIMESTAMP NOT NULL,
    reason VARCHAR(512)
);

CREATE INDEX idx_charge_agreements_customer_status_validity
    ON charge_agreements(customer_id, status, valid_from, valid_to);

CREATE INDEX idx_charge_agreements_lane_customer_validity
    ON charge_agreements(trade_lane_id, customer_id, valid_from, valid_to);

CREATE TABLE IF NOT EXISTS manual_pricing_cases (
    case_id VARCHAR(64) PRIMARY KEY,
    pricing_request_id VARCHAR(128) NOT NULL,
    reason_code VARCHAR(128) NOT NULL,
    correlation_id VARCHAR(128),
    opened_at TIMESTAMP,
    snapshot TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_manual_pricing_cases_request
    ON manual_pricing_cases(pricing_request_id);

CREATE TABLE IF NOT EXISTS pricing_requests (
    idempotency_key VARCHAR(160) PRIMARY KEY,
    booking_ref VARCHAR(128) NOT NULL,
    amendment_seq INTEGER NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    owner_token VARCHAR(128),
    lease_until TIMESTAMP,
    response_snapshot TEXT,
    terminal_code VARCHAR(128),
    correlation_id VARCHAR(128),
    started_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    UNIQUE (booking_ref, amendment_seq)
);

CREATE INDEX IF NOT EXISTS idx_pricing_requests_status_lease
    ON pricing_requests(status, lease_until);

CREATE TABLE IF NOT EXISTS charge_agreement_outbox (
    event_id VARCHAR(128) PRIMARY KEY,
    event_type VARCHAR(128) NOT NULL,
    agreement_id VARCHAR(64) NOT NULL,
    agreement_status VARCHAR(32) NOT NULL,
    agreement_version BIGINT NOT NULL,
    schema_subject VARCHAR(128) NOT NULL,
    producer_identity VARCHAR(128) NOT NULL,
    deduplication_key VARCHAR(256) NOT NULL,
    correlation_id VARCHAR(128),
    occurred_at TIMESTAMP,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP,
    claimed_by VARCHAR(128),
    claimed_at TIMESTAMP,
    last_error_code VARCHAR(128),
    last_error_message VARCHAR(1024),
    snapshot TEXT NOT NULL
);

ALTER TABLE charge_agreement_outbox ADD COLUMN IF NOT EXISTS status VARCHAR(32) NOT NULL DEFAULT 'PENDING';
ALTER TABLE charge_agreement_outbox ADD COLUMN IF NOT EXISTS attempt_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE charge_agreement_outbox ADD COLUMN IF NOT EXISTS next_attempt_at TIMESTAMP;
ALTER TABLE charge_agreement_outbox ADD COLUMN IF NOT EXISTS claimed_by VARCHAR(128);
ALTER TABLE charge_agreement_outbox ADD COLUMN IF NOT EXISTS claimed_at TIMESTAMP;
ALTER TABLE charge_agreement_outbox ADD COLUMN IF NOT EXISTS last_error_code VARCHAR(128);
ALTER TABLE charge_agreement_outbox ADD COLUMN IF NOT EXISTS last_error_message VARCHAR(1024);

CREATE INDEX IF NOT EXISTS idx_charge_agreement_outbox_agreement
    ON charge_agreement_outbox(agreement_id, occurred_at);

CREATE INDEX IF NOT EXISTS idx_charge_agreement_outbox_claim
    ON charge_agreement_outbox(status, next_attempt_at, occurred_at);
