CREATE TABLE IF NOT EXISTS container_journeys (
    journey_id VARCHAR(64) PRIMARY KEY,
    booking_id VARCHAR(64) NOT NULL,
    booking_revision INTEGER NOT NULL,
    container_id VARCHAR(128) NOT NULL,
    movement_status VARCHAR(32) NOT NULL,
    updated_at TIMESTAMP,
    snapshot TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_container_journeys_booking
    ON container_journeys(booking_id, updated_at);

CREATE INDEX IF NOT EXISTS idx_container_journeys_container_status
    ON container_journeys(container_id, movement_status);

ALTER TABLE container_journeys ALTER COLUMN container_id TYPE VARCHAR(128);

CREATE TABLE IF NOT EXISTS container_movement_idempotency (
    idempotency_key VARCHAR(128) PRIMARY KEY,
    journey_id VARCHAR(64),
    movement_event_id VARCHAR(128),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS container_movement_audit (
    audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action VARCHAR(64) NOT NULL,
    journey_id VARCHAR(64),
    actor_subject_id VARCHAR(128),
    outcome VARCHAR(32) NOT NULL,
    reason_code VARCHAR(128),
    correlation_id VARCHAR(128),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_container_movement_audit_journey
    ON container_movement_audit(journey_id, created_at);

CREATE TABLE IF NOT EXISTS container_movement_outbox (
    event_id VARCHAR(128) PRIMARY KEY,
    event_type VARCHAR(128) NOT NULL,
    journey_id VARCHAR(64) NOT NULL,
    booking_id VARCHAR(64) NOT NULL,
    container_id VARCHAR(128) NOT NULL,
    movement_status VARCHAR(32) NOT NULL,
    schema_subject VARCHAR(128) NOT NULL,
    producer_identity VARCHAR(128) NOT NULL,
    deduplication_key VARCHAR(128) NOT NULL,
    correlation_id VARCHAR(128),
    occurred_at TIMESTAMP,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP,
    claimed_by VARCHAR(128),
    claimed_at TIMESTAMP,
    last_error_code VARCHAR(128),
    last_error_message VARCHAR(1024),
    snapshot TEXT NOT NULL
);

ALTER TABLE container_movement_outbox ADD COLUMN IF NOT EXISTS movement_status VARCHAR(32) NOT NULL DEFAULT 'CREATED';
ALTER TABLE container_movement_outbox ALTER COLUMN container_id TYPE VARCHAR(128);
ALTER TABLE container_movement_outbox ADD COLUMN IF NOT EXISTS status VARCHAR(32) NOT NULL DEFAULT 'PENDING';
ALTER TABLE container_movement_outbox ADD COLUMN IF NOT EXISTS attempt_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE container_movement_outbox ADD COLUMN IF NOT EXISTS next_attempt_at TIMESTAMP;
ALTER TABLE container_movement_outbox ADD COLUMN IF NOT EXISTS claimed_by VARCHAR(128);
ALTER TABLE container_movement_outbox ADD COLUMN IF NOT EXISTS claimed_at TIMESTAMP;
ALTER TABLE container_movement_outbox ADD COLUMN IF NOT EXISTS last_error_code VARCHAR(128);
ALTER TABLE container_movement_outbox ADD COLUMN IF NOT EXISTS last_error_message VARCHAR(1024);

UPDATE container_movement_outbox
SET movement_status = status,
    status = 'PENDING'
WHERE status NOT IN ('PENDING', 'CLAIMED', 'PUBLISHED', 'FAILED_RETRYABLE', 'FAILED_PERMANENT');

CREATE INDEX IF NOT EXISTS idx_container_movement_outbox_journey
    ON container_movement_outbox(journey_id, occurred_at);

CREATE INDEX IF NOT EXISTS idx_container_movement_outbox_claim
    ON container_movement_outbox(status, next_attempt_at, occurred_at);
