server {
  listen 80;

  location /auth/ {
    rewrite ^/auth/(.*)$ /$1 break;
    proxy_pass http://apps-auth:3000;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Correlation-Id $request_id;
  }

  location /reference-data/ {
    proxy_pass http://apps-reference-data:3000/;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Correlation-Id $request_id;
  }

  location = /charge-agreements {
    return 308 /charge-agreements/;
  }

  location ^~ /charge-agreements/ {
    proxy_pass http://apps-charge-agreements:3000;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Correlation-Id $request_id;
  }

  location /health {
    return 200 "ok\n";
  }

  location = /bookings {
    proxy_pass http://apps-shell:3000/bookings;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Correlation-Id $request_id;
  }

  location /bookings/ {
    proxy_pass http://apps-shell:3000/bookings/;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Correlation-Id $request_id;
  }

  location = /booking {
    proxy_pass http://apps-shell:3000/booking;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Correlation-Id $request_id;
  }

  location /booking/ {
    proxy_pass http://apps-shell:3000/booking/;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Correlation-Id $request_id;
  }

  location / {
    proxy_pass http://apps-shell:3000;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Correlation-Id $request_id;
  }
}
