server {
  listen 80;

  location /auth/ {
    proxy_pass http://apps-auth:3000/;
    proxy_set_header X-Correlation-Id $request_id;
  }

  location /reference-data/ {
    proxy_pass http://apps-reference-data:3000/;
    proxy_set_header X-Correlation-Id $request_id;
  }

  location /health {
    return 200 "ok\n";
  }
}
